module.exports = {
  asq: [
    { q: "What is the capital of France?", a: "Paris", accept: ["paris"] },
    { q: "What is the capital of Japan?", a: "Tokyo", accept: ["tokyo"] },
    { q: "What is the capital of Canada?", a: "Ottawa", accept: ["ottawa"] },
    { q: "What is the capital of Brazil?", a: "Brasilia", accept: ["brasilia"] },
    { q: "What is the capital of Egypt?", a: "Cairo", accept: ["cairo"] },
    { q: "What is the capital of New Zealand?", a: "Wellington", accept: ["wellington"] },
    { q: "What is the capital of Kenya?", a: "Nairobi", accept: ["nairobi"] },
    { q: "What is the capital of South Korea?", a: "Seoul", accept: ["seoul"] },
    { q: "What is the capital of Spain?", a: "Madrid", accept: ["madrid"] },
    { q: "What is the capital of Italy?", a: "Rome", accept: ["rome"] },
    { q: "What is the capital of Germany?", a: "Berlin", accept: ["berlin"] },
    { q: "What is the capital of India?", a: "New Delhi", accept: ["new delhi", "delhi"] },
    { q: "What is the capital of China?", a: "Beijing", accept: ["beijing"] },
    { q: "What is the capital of Mexico?", a: "Mexico City", accept: ["mexico city", "mexico"] },
    { q: "What is the capital of Turkey?", a: "Ankara", accept: ["ankara"] },
    { q: "What is the capital of Argentina?", a: "Buenos Aires", accept: ["buenos aires"] },
    { q: "Which is the largest ocean on Earth?", a: "Pacific Ocean", accept: ["pacific ocean", "the pacific", "pacific"] },
    { q: "Which is the largest hot desert in the world?", a: "Sahara Desert", accept: ["sahara desert", "sahara"] },
    { q: "What is the longest river in Africa?", a: "Nile River", accept: ["nile river", "the nile", "nile"] },
    { q: "Which mountain range forms part of the border between Europe and Asia?", a: "Ural Mountains", accept: ["ural mountains", "the urals", "urals"] },
    { q: "Which is the largest country in the world by land area?", a: "Russia", accept: ["russia"] },
    { q: "Which continent is Egypt located in?", a: "Africa", accept: ["africa"] },
    { q: "Which strait separates Spain from Morocco?", a: "Strait of Gibraltar", accept: ["strait of gibraltar", "gibraltar strait", "gibraltar"] },
    { q: "What is the highest mountain above sea level?", a: "Mount Everest", accept: ["mount everest", "everest"] },
    { q: "Which country is often described as being shaped like a boot?", a: "Italy", accept: ["italy"] },
    { q: "Off the coast of which country lies the Great Barrier Reef?", a: "Australia", accept: ["australia"] },
    { q: "Which two continents are linked by the Suez Canal?", a: "Africa and Asia", accept: ["africa and asia", "africa asia"] },
    { q: "Which imaginary line divides the Northern and Southern hemispheres?", a: "Equator", accept: ["equator", "the equator"] },
    { q: "What is the smallest country in the world?", a: "Vatican City", accept: ["vatican city", "vatican"] },
    { q: "Which continent contains the Amazon rainforest?", a: "South America", accept: ["south america"] },
    { q: "Which gas makes up most of Earth's atmosphere?", a: "Nitrogen", accept: ["nitrogen"] },
    { q: "Which planet is known as the Red Planet?", a: "Mars", accept: ["mars"] },
    { q: "Which planet in our solar system is closest to the Sun?", a: "Mercury", accept: ["mercury"] },
    { q: "What is the largest planet in the solar system?", a: "Jupiter", accept: ["jupiter"] },
    { q: "Which organ pumps blood around the human body?", a: "Heart", accept: ["heart", "the heart"] },
    { q: "What is the hardest natural substance known to science?", a: "Diamond", accept: ["diamond"] },
    { q: "Which element has the chemical symbol Au?", a: "Gold", accept: ["gold"] },
    { q: "What is the process by which plants make their own food?", a: "Photosynthesis", accept: ["photosynthesis"] },
    { q: "Which part of a cell contains its genetic material?", a: "Nucleus", accept: ["nucleus"] },
    { q: "How many bones are there in the adult human body?", a: "206 bones", accept: ["206 bones"] },
    { q: "What is the scientific study of earthquakes called?", a: "Seismology", accept: ["seismology"] },
    { q: "What do you call a study of ancient plants?", a: "Paleobotany", accept: ["paleobotany", "palaeobotany"] },
    { q: "What is the scientific study of insects called?", a: "Entomology", accept: ["entomology"] },
    { q: "What is the scientific study of birds called?", a: "Ornithology", accept: ["ornithology"] },
    { q: "What is the scientific study of fungi called?", a: "Mycology", accept: ["mycology"] },
    { q: "What is the study of the origins of words called?", a: "Etymology", accept: ["etymology"] },
    { q: "What do you call a person who studies stars and planets?", a: "Astronomer", accept: ["astronomer"] },
    { q: "What is the boiling point of water in degrees Celsius?", a: "100 degrees", accept: ["100 degrees", "one hundred degrees"] },
    { q: "What is the freezing point of water in degrees Celsius?", a: "Zero degrees", accept: ["zero degrees", "0 degrees"] },
    { q: "How many days are there in a leap year?", a: "366 days", accept: ["366 days"] },
    { q: "What force pulls objects toward the surface of the Earth?", a: "Gravity", accept: ["gravity"] },
    { q: "A dolphin belongs to which class of animals?", a: "Mammal", accept: ["mammal", "mammals"] },
    { q: "What sweet substance do bees collect from flowers?", a: "Nectar", accept: ["nectar"] },
    { q: "What is the chemical formula H2O commonly known as?", a: "Water", accept: ["water"] },
    { q: "Which type of blood cell fights infection in the body?", a: "White blood cells", accept: ["white blood cells", "leukocytes", "leucocytes"] },
    { q: "What do you call an animal that eats only plants?", a: "Herbivore", accept: ["herbivore", "plant eater"] },
    { q: "What is the scientific study of weather called?", a: "Meteorology", accept: ["meteorology"] },
    { q: "Which word describes animals that are active mainly at night?", a: "Nocturnal", accept: ["nocturnal"] },
    { q: "What is the solid outer layer of the Earth called?", a: "Crust", accept: ["crust", "earth crust"] },
    { q: "What is the process by which cells release energy from glucose?", a: "Respiration", accept: ["respiration", "cellular respiration"] },
    { q: "What does the word ubiquitous mean?", a: "Everywhere", accept: ["everywhere", "in every place", "all places"] },
    { q: "What is an obvious typing mistake in a written text called?", a: "Typo", accept: ["typo", "typographical error"] },
    { q: "What is a short summary placed at the start of a paper called?", a: "Abstract", accept: ["abstract"] },
    { q: "What is a list of sources at the end of a book called?", a: "Bibliography", accept: ["bibliography"] },
    { q: "What is the main argument of an essay called?", a: "Thesis", accept: ["thesis", "central argument"] },
    { q: "What do you call a word that imitates a natural sound?", a: "Onomatopoeia", accept: ["onomatopoeia"] },
    { q: "What is the opposite of a synonym called?", a: "Antonym", accept: ["antonym"] },
    { q: "What do you call a comparison using the words like or as?", a: "Simile", accept: ["simile"] },
    { q: "What do you call language that gives human traits to objects?", a: "Personification", accept: ["personification"] },
    { q: "What is the final section of a report called?", a: "Conclusion", accept: ["conclusion"] },
    { q: "What do you call rewriting a source text in your own words?", a: "Paraphrasing", accept: ["paraphrasing", "paraphrase"] },
    { q: "What do you call a word that means the same as another?", a: "Synonym", accept: ["synonym"] },
    { q: "What is a group of sentences that develops one idea called?", a: "Paragraph", accept: ["paragraph"] },
    { q: "What do you call a detailed written study of a single case?", a: "Case study", accept: ["case study", "case studies"] },
    { q: "What diagram shows the steps of a process in order?", a: "Flow chart", accept: ["flow chart", "flowchart", "process diagram"] },
    { q: "What kind of evidence comes directly from observation or experiment?", a: "Empirical evidence", accept: ["empirical evidence", "empirical data"] },
    { q: "What is the middle value of a data set called?", a: "Median", accept: ["median"] },
    { q: "What is the most frequent value in a data set called?", a: "Mode", accept: ["mode"] },
    { q: "What is the average of a set of numbers called?", a: "Mean", accept: ["mean", "average"] },
    { q: "What do you call an explanation that can be tested?", a: "Hypothesis", accept: ["hypothesis"] },
    { q: "What do you call a person taking part in a study?", a: "Participant", accept: ["participant", "subject"] },
    { q: "What is a review of earlier research in a thesis called?", a: "Literature review", accept: ["literature review", "review of literature"] },
    { q: "What do you call a factor that may distort an experiment?", a: "Confounding variable", accept: ["confounding variable", "confounding factor"] },
    { q: "What is presenting other people's ideas as your own called?", a: "Plagiarism", accept: ["plagiarism"] },
    { q: "What do you call a plan that sets times for studying?", a: "Study schedule", accept: ["study schedule", "study plan", "study timetable"] },
    { q: "What is the process of reviewing notes to remember them called?", a: "Revision", accept: ["revision", "review"] },
    { q: "What do you call a quick first reading to get the gist?", a: "Skimming", accept: ["skimming"] },
    { q: "What do you call reading carefully to find specific information?", a: "Scanning", accept: ["scanning"] },
    { q: "What study method involves testing yourself with flashcards?", a: "Active recall", accept: ["active recall", "self testing"] },
    { q: "What is a study method using short bursts and breaks called?", a: "Pomodoro technique", accept: ["pomodoro technique", "pomodoro method", "pomodoro"] },
    { q: "What do you call a clear question that guides a research project?", a: "Research question", accept: ["research question", "research problem"] },
    { q: "What is an alphabetical list of topics in a book called?", a: "Index", accept: ["index"] },
    { q: "What is the central message of a passage called?", a: "Main idea", accept: ["main idea", "central idea"] },
    { q: "What do you call reviewing material at spaced intervals over days?", a: "Spaced repetition", accept: ["spaced repetition", "spaced practice"] },
    { q: "What do you call a question asked to check understanding?", a: "Clarifying question", accept: ["clarifying question", "clarification question"] },
    { q: "What do you call a small class led by a tutor?", a: "Tutorial", accept: ["tutorial", "tutorial class"] },
    { q: "What is the total number of words in an essay called?", a: "Word count", accept: ["word count", "word limit"] },
    { q: "Where do students borrow books on campus?", a: "Library", accept: ["library", "the library"] },
    { q: "What is a fee for an overdue library book called?", a: "Fine", accept: ["fine", "late fee", "overdue fine"] },
    { q: "Which campus office issues official academic transcripts?", a: "Registrar", accept: ["registrar", "registrar office", "records office"] },
    { q: "Who helps students choose courses and plan their degrees?", a: "Academic adviser", accept: ["academic adviser", "academic advisor", "adviser", "advisor"] },
    { q: "What document shows that you have completed a degree?", a: "Diploma", accept: ["diploma"] },
    { q: "What do you call a student who has finished their studies?", a: "Graduate", accept: ["graduate"] },
    { q: "What kind of funding does not have to be repaid?", a: "Grant", accept: ["grant", "grants", "bursary"] },
    { q: "What document allows you to enter a country to study?", a: "Visa", accept: ["visa", "student visa"] },
    { q: "What is the introductory period for new students before classes begin?", a: "Orientation", accept: ["orientation", "orientation week", "induction week"] },
    { q: "Where should you report a problem with your accommodation?", a: "Housing office", accept: ["housing office", "accommodation office", "residence office"] },
    { q: "What is the main place where students eat on campus called?", a: "Cafeteria", accept: ["cafeteria", "dining hall", "canteen"] },
    { q: "What eye protection must you wear in a chemistry laboratory?", a: "Safety goggles", accept: ["safety goggles", "protective goggles", "goggles"] },
    { q: "What document records an accident that happens in a laboratory?", a: "Incident report", accept: ["incident report", "accident report"] },
    { q: "Who can students see for help with stress and personal problems?", a: "Counsellor", accept: ["counsellor", "counselor", "student counsellor", "student counselor"] },
    { q: "What do you call a job that fits around your classes?", a: "Part-time job", accept: ["part-time job", "part time job", "temporary job"] },
    { q: "Which organisation represents students and runs campus events?", a: "Student union", accept: ["student union", "students union", "students' union"] },
    { q: "What do you call a talk given to a large group of students?", a: "Lecture", accept: ["lecture", "lectures"] },
    { q: "What is the process of reserving a campus room called?", a: "Room booking", accept: ["room booking", "room reservation", "booking"] },
    { q: "What machine produces paper copies of a document?", a: "Photocopier", accept: ["photocopier", "copy machine"] },
    { q: "What is the money paid to the university each term called?", a: "Tuition fee", accept: ["tuition fee", "tuition fees", "course fee"] },
    { q: "What is the final day for handing in an assignment called?", a: "Due date", accept: ["due date", "deadline"] },
    { q: "Where can students get free help with their written work?", a: "Writing centre", accept: ["writing centre", "writing center", "writing lab"] },
    { q: "What document proves your identity on campus?", a: "Student card", accept: ["student card", "student id", "identity card"] },
    { q: "What kind of scholarship is based on academic merit?", a: "Merit scholarship", accept: ["merit scholarship", "academic scholarship"] },
    { q: "What document do you show when passing through airport security?", a: "Passport", accept: ["passport"] },
    { q: "What do you call money returned after you bring an item back?", a: "Refund", accept: ["refund"] },
    { q: "What document shows the price you paid for your shopping?", a: "Receipt", accept: ["receipt"] },
    { q: "What do you call a place where travelers exchange money?", a: "Currency exchange", accept: ["currency exchange", "bureau de change", "money exchange"] },
    { q: "What do you call a card used to pay for bus journeys?", a: "Travel card", accept: ["travel card", "transit card", "bus pass"] },
    { q: "What device gives you turn by turn directions on a road?", a: "Navigation app", accept: ["navigation app", "maps app", "gps application"] },
    { q: "Which appliance keeps food cold to stop it spoiling?", a: "Refrigerator", accept: ["refrigerator", "fridge"] },
    { q: "What do you plug into a socket to charge a phone?", a: "Charger", accept: ["charger", "phone charger", "charging device"] },
    { q: "What do you call a suitcase that you carry onto a plane?", a: "Hand luggage", accept: ["hand luggage", "carry-on luggage", "carry on luggage", "cabin baggage"] },
    { q: "What do you call an agreement to pay for a service monthly?", a: "Subscription", accept: ["subscription", "monthly plan", "service plan"] },
    { q: "What is the amount of money owed on a credit card called?", a: "Balance", accept: ["balance", "outstanding balance"] },
    { q: "What do you call a doctor who treats children?", a: "Pediatrician", accept: ["pediatrician", "paediatrician", "children's doctor"] },
    { q: "What do you call a reduction in the price of an item?", a: "Discount", accept: ["discount", "price reduction", "special offer"] },
    { q: "What do you call regular payments for hourly work?", a: "Wages", accept: ["wages", "hourly pay"] },
    { q: "What document lists your work history and skills?", a: "Curriculum vitae", accept: ["curriculum vitae", "resume", "vita"] },
    { q: "What do you call a formal meeting for a job application?", a: "Interview", accept: ["interview", "job interview"] },
    { q: "What word describes a person who speaks two languages fluently?", a: "Bilingual", accept: ["bilingual"] },
    { q: "What letter accompanies a job application and introduces you?", a: "Cover letter", accept: ["cover letter", "application letter"] },
    { q: "What number is one quarter of two hundred?", a: "Fifty", accept: ["fifty"] },
    { q: "How many minutes are there in two hours?", a: "120 minutes", accept: ["120 minutes", "one hundred and twenty minutes"] },
    { q: "Which meal is typically eaten in the morning?", a: "Breakfast", accept: ["breakfast"] },
    { q: "What do you call a person who writes dictionary entries?", a: "Lexicographer", accept: ["lexicographer", "lexicologist"] },
    { q: "What map shows physical features such as hills and valleys?", a: "Topographic map", accept: ["topographic map", "topographical map", "relief map"] },
    { q: "What do you call a scholar who teaches at a university?", a: "Professor", accept: ["professor"] },
    { q: "What do you call research based on existing publications rather than fieldwork?", a: "Secondary research", accept: ["secondary research", "desk research"] },
    { q: "What is a score expressed out of one hundred called?", a: "Percentage", accept: ["percentage", "percent"] }
  ],
  rs: [
    "You must register for your courses before the end of next week.",
    "Course registration for the new semester opens on the first Monday.",
    "Students who miss the registration deadline must pay a late fee.",
    "Places in the advanced module are limited, so register as early as possible.",
    "You can change your registered courses during the first two weeks.",
    "Please confirm your chosen modules through the online student portal.",
    "The registrar will review your enrolment form within three working days.",
    "You may add an elective course without any additional charge.",
    "Every student must complete the online registration before attending any class.",
    "If the module is full, you will be placed on a waiting list.",
    "Your timetable will be available to download once registration is confirmed.",
    "Transfer students should bring their previous academic records during registration week.",
    "Part time students may register for fewer courses each semester.",
    "Registration closes at noon on the final Friday of the week.",
    "The system will not accept your registration without a valid email address.",
    "All written assignments must be uploaded before midnight on the due date.",
    "Extensions for deadlines are granted only in exceptional circumstances.",
    "Your tutor will explain the late submission policy in the first class.",
    "Please keep a copy of every file you submit for assessment.",
    "The deadline for the research project falls at the end of March.",
    "Late work receives a reduced mark even if the content is strong.",
    "You should check the submission portal well before the final deadline.",
    "Group projects must be submitted by one nominated member of the team.",
    "Deadlines are strict because markers begin grading immediately after the cut off.",
    "Draft essays can be submitted early for informal feedback from your tutor.",
    "Missing a deadline without a reason will lower your final grade.",
    "The academic calendar lists every important deadline for the whole year.",
    "The final examination will be held in the main sports hall.",
    "You must arrive at the examination room fifteen minutes before it starts.",
    "Mobile phones must be switched off and left outside the exam hall.",
    "Practice tests are available online to help you prepare for the examination.",
    "Students with approved support arrangements will receive extra examination time.",
    "You may bring a calculator only if the subject requires one.",
    "The invigilator will read the instructions before the paper begins.",
    "Results for the main examinations are usually published within four weeks.",
    "You cannot leave the examination room during the first thirty minutes.",
    "Past papers from previous years are kept in the library for reference.",
    "An official medical certificate is required if you miss an examination.",
    "Quiet study spaces are reserved for students preparing for their finals.",
    "The library houses over half a million books across four floors.",
    "Borrowed books must be returned or renewed before the due date.",
    "A small fine is charged for each day a book is overdue.",
    "The library provides free group rooms that students can reserve online.",
    "Interlibrary loans usually arrive within five working days of your request.",
    "Quiet floors are reserved for individual study and silent reading only.",
    "Your student card allows you to borrow up to twelve items.",
    "Journal articles can be downloaded from the library database at any time.",
    "The help desk offers training sessions on how to find academic sources.",
    "Rare manuscripts are kept in a special collection and cannot be borrowed.",
    "Printing and photocopying services are available on every level of the building.",
    "The reading room stays open later during the main examination period.",
    "Safety goggles must be worn whenever chemicals are handled in the laboratory.",
    "Long hair must be tied back before you enter the science lab.",
    "Report every spillage to your instructor before continuing with the experiment.",
    "The emergency shower is located beside the door of each laboratory.",
    "Open shoes and loose clothing are not permitted in the practical sessions.",
    "All chemical waste must be poured into the labelled disposal containers.",
    "Your laboratory supervisor will demonstrate each procedure before you attempt it.",
    "Fire extinguishers are checked regularly by the campus safety team.",
    "Never taste or smell an unknown substance during a laboratory exercise.",
    "Protective gloves should be worn when you work with strong acids.",
    "Accident report forms are kept in the cabinet next to the entrance.",
    "The safety induction must be completed before your first laboratory session.",
    "Campus residences are allocated to first year students by the housing office.",
    "Your room key must be collected from the reception desk before six.",
    "Rent for university accommodation is paid at the start of each term.",
    "Maintenance requests can be submitted through the online accommodation portal.",
    "Shared kitchens are cleaned weekly by the residential support team.",
    "Visitors are not permitted to stay overnight in the student residences.",
    "A refundable deposit is required when you accept a room offer.",
    "The residence hall has a common room for social events and meetings.",
    "You should report any faulty equipment to the front desk immediately.",
    "Contract lengths for halls of residence match the academic year exactly.",
    "Laundry facilities are available in the basement of every student building.",
    "Off campus housing listings are published on the university accommodation website.",
    "Academic writing workshops are held every Wednesday afternoon during term time.",
    "Attendance at the research methods workshop counts toward your training record.",
    "You can book a place at any workshop through the student portal.",
    "The statistics workshop includes practical exercises using real research data sets.",
    "Places at the academic skills sessions are limited and allocated quickly.",
    "All workshop materials are uploaded to the learning platform after each session.",
    "The library runs introductory workshops on referencing at the start of semester.",
    "Workshop facilitators will answer questions at the end of every session.",
    "The presentation skills workshop helps students speak clearly and confidently.",
    "Certificates are issued to students who attend the full workshop series.",
    "Free tutoring sessions are available for students taking first year mathematics.",
    "Your tutor can help you plan essays and structure your arguments.",
    "Peer tutors are trained undergraduates who have performed well in the subject.",
    "Tutoring appointments last forty five minutes and can be booked online.",
    "The tutoring centre is open on weekdays from nine until five.",
    "Bring your draft work to the session so the tutor can advise you.",
    "Small group tutoring is offered for students who prefer shared learning.",
    "Tutoring focuses on your own work rather than on general revision.",
    "Students who attend tutoring regularly tend to improve their grades significantly.",
    "You may meet the same tutor throughout the entire academic year.",
    "The student union organises clubs, events, and support services on campus.",
    "Election nominations for the student union open early next month.",
    "The union shop sells stationery, snacks, and essential supplies at low prices.",
    "Student representatives meet the union committee every second Thursday of the month.",
    "The union provides advice if you have a dispute with the university.",
    "Freshers week is organised by the student union for new arrivals.",
    "Funding for student societies is decided by the union each March.",
    "The union building has a cafe, a prayer room, and study spaces.",
    "You can raise a complaint anonymously through the student union website.",
    "Union membership is automatic for every enrolled student at the university.",
    "Seminar rooms can be reserved up to two weeks in advance.",
    "Unclaimed bookings are released fifteen minutes after the scheduled start time.",
    "The online booking system shows which rooms are free for your group.",
    "Large lecture halls require approval from the timetabling office before booking.",
    "You must vacate the room promptly because another class follows yours.",
    "Study pods near the library can be booked in hourly slots.",
    "Cancel your reservation early so other students can use the space.",
    "Rooms equipped with projectors are marked clearly in the booking calendar.",
    "Bookings for evening events end no later than eleven at night.",
    "The reception desk can arrange a room booking if the system fails.",
    "Tuition fees may be paid in full or in three instalments.",
    "A student loan will cover your fees if your application is approved.",
    "Late payment of fees may prevent you from receiving your results.",
    "Bank transfers usually take two working days to reach the university.",
    "The finance office issues official receipts for every completed payment.",
    "International students must show proof of funding before their enrolment is confirmed.",
    "Payment plans can be arranged for students facing short term hardship.",
    "Your student account balance is updated within twenty four hours of payment.",
    "Scholarships are deducted from your fees before the payment deadline.",
    "Please quote your student number whenever you make a payment.",
    "Orientation week introduces new students to the campus and its services.",
    "The welcome talk begins at ten in the morning on Monday.",
    "Faculty tours run throughout the day and need no advance booking.",
    "Orientation includes sessions on academic integrity and proper referencing practices.",
    "You will receive a campus map and a student handbook during induction.",
    "International students attend a separate briefing about visa and immigration rules.",
    "The careers service explains internship opportunities during the orientation programme.",
    "Sport clubs hold introductory fairs where you can try new activities.",
    "Orientation is a good time to meet your course coordinator and classmates.",
    "Bus routes and travel passes are explained in the arrival guide."
  ]
};
